### ISSUE TITLE
How can I "install" apaka?

### ISSUE THREAD

**Issue by AlexanderFabisch** [2maz/apaka#1]
I tried to clone it in my autoproj workspace and to compile it with amake. This is the result:

```
updated: /home/dfki.uni-bremen.de/afabisch/tmp/test_buildconf/env.sh
  ERROR: manifest /home/dfki.uni-bremen.de/afabisch/tmp/test_buildconf/tools/apaka/manifest.xml of tools/apaka from main configuration lists 'autoproj' as dependency, but it is neither a normal package nor an osdeps package. osdeps reports: cannot resolve autoproj: autoproj is not an osdep and it cannot be resolved as a source package
```

**Comment by AlexanderFabisch** [comment]
OK, since autoproj is now optional `amake` runs successfully. I have another problem: none of the scripts from bin/ are installed. I also tried to run rake install but it does not work.

**Comment by 2maz** [comment]
Rake install will not work.
Using amake will auto-detect and auto-add this package as ruby_package, and as a result extend RUBYLIB etc., so opening a new shell and sourcing is required as mentioned in the README, but I assume you did that already?

Otherwise,  what happens when you
```
aup <path-to-apaka>
amake <path-to-apaka>
autoproj envsh
```

**Comment by AlexanderFabisch** [comment]
> Using amake will auto-detect and auto-add this package as ruby_package, and as a result extend RUBYLIB etc., so opening a new shell and sourcing is required as mentioned in the README, but I assume you did that already?

yes



> Otherwise, what happens when you
> 
> aup <path-to-apaka>
> amake <path-to-apaka>
> autoproj envsh

nothing

The scripts are not installed to $AUTOPROJ_CURRENT_ROOT/bin. How is it supposed to work exactly?

**Comment by 2maz** [comment]
Ok my fault, it should be only as stated in the README:
```
aup
amake
```
The PATH environment variable is updated by autoproj, when you call amake, 
so that it points to apaka's bin folder.
Calling autoproj envsh deleted this change, since it requires the package to be explicitly added to autoproj/manifest.

**Comment by AlexanderFabisch** [comment]
It still does not work in my setup but that does not seem to be a problem of apaka. Closing this issue.
