### ISSUE TITLE
Cannot run deb_local --prepare, apache2 service does not start

### ISSUE THREAD

**Issue by AlexanderFabisch** [2maz/apaka#2]
I am running the following command:

    bin/deb_local --prepare --architecture amd64 --distribution xenial --release-name master-18.05

This is the result:

```
Installer[INFO]: 'apache2' is already installed
/home/dfki.uni-bremen.de/afabisch/.autoproj/gems/ruby/2.3.0/gems/apaka-0.1.0/lib/apaka/packaging/installer.rb:32:in `ensure_webserver_running': Apaka::Packaging::Installer: failed to start webserver -- Failed to start apache2.service: Unit apache2.service not found. (RuntimeError)
```

**Comment by 2maz** [comment]
What operating system are you running on? 
Can you check the status of apache manually and post the result.

**Comment by AlexanderFabisch** [comment]
Ubuntu 16.04

```
$ sudo service apache2 status
[sudo] Passwort für afabisch: 
● apache2.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

apache2 does not seem to be installed. I don't know why apaka thinks it is?! How is it checked?

**Comment by 2maz** [comment]
dpkg -l, but using only the command return value, so checking on 'install' status with the following command fixes the issue.
```
dpkg-query -W -f='${db:Status-Want} <packagename>

**Comment by AlexanderFabisch** [comment]
OK, works!
